version: "3"
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - mynet

  app:
    build: .
    expose:
      - "5000"
    networks:
      - mynet

  redis:
    image: redis:alpine
    networks:
      - mynet

networks:
  mynet:  


